// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX_4X9m4XdbBb0Im35K5_sAVD3EPdTDvM',
    appId: '1:788559741966:web:d28b0b850187a25d4b285f',
    messagingSenderId: '788559741966',
    projectId: 'sonix-plan-aa359',
    authDomain: 'sonix-plan-aa359.firebaseapp.com',
    storageBucket: 'sonix-plan-aa359.firebasestorage.app',
    measurementId: 'G-VMK5NL4JHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhlTlsovoupivTcRZ2qk4FqDgjTSeTRgU',
    appId: '1:788559741966:android:3ba73294d7b24c5b4b285f',
    messagingSenderId: '788559741966',
    projectId: 'sonix-plan-aa359',
    storageBucket: 'sonix-plan-aa359.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB34FTv3xOhA-Xr8DnzEgpATCByGls36Ag',
    appId: '1:788559741966:ios:1c7bfb104557df5a4b285f',
    messagingSenderId: '788559741966',
    projectId: 'sonix-plan-aa359',
    storageBucket: 'sonix-plan-aa359.firebasestorage.app',
    iosBundleId: 'com.example.sonixPlan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB34FTv3xOhA-Xr8DnzEgpATCByGls36Ag',
    appId: '1:788559741966:ios:1c7bfb104557df5a4b285f',
    messagingSenderId: '788559741966',
    projectId: 'sonix-plan-aa359',
    storageBucket: 'sonix-plan-aa359.firebasestorage.app',
    iosBundleId: 'com.example.sonixPlan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX_4X9m4XdbBb0Im35K5_sAVD3EPdTDvM',
    appId: '1:788559741966:web:83c40a945cbaaea64b285f',
    messagingSenderId: '788559741966',
    projectId: 'sonix-plan-aa359',
    authDomain: 'sonix-plan-aa359.firebaseapp.com',
    storageBucket: 'sonix-plan-aa359.firebasestorage.app',
    measurementId: 'G-MSNSNJRWN5',
  );
}
